var data_kinang = [
    {
        "id": "1",
        "ten": "Gnawing",
        "img": "Atk-Dark",
        "phep": "0",
        "hp": "0",
        "level": "5",
        "vatli": "30",
        "mp": "2",
        "thoigian": "2500",
        "rong": "320",
        "cao": "64",
        "x": "-30",
        "w": "50",
        "h": "50",
        "sohinh": "5",
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ.Gây (Sát thương vật lí + 50*lv skill)"
    },
    {
        "id": "2",
        "ten": "Poison fire",
        "img": "Atk-Dragon",
        "phep": "40",
        "level": "5",
        "hp": "0",
        "vatli": "0",
        "mp": "5",
        "x": "-30",
        "thoigian": "3500",
        "rong": "384",
        "cao": "64",
        "sohinh": "6",
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt.Gây sát thương phép + 70*lv kĩ năng."
    },
    {
        "id": "3",
        "ten": "Ghosts",
        "img": "Atk-Ghost",
        "phep": "60",
        "level": "10",
        "hp": "0",
        "vatli": "0",
        "mp": "5",
        "x": "-30",
        "thoigian": "2500",
        "rong": "384",
        "w": 50,
        "h": 50,
        "cao": "64",
        "sohinh": "6",
        "mota": "Gọi ra hồn ma gây sát thương cho đối thủ stp + 50* level kĩ năng."
    },
    {
        "id": "4",
        "ten": "Devils eye",
        "img": "Atk-Psychic",
        "phep": "0",
        "hp": "0",
        "level": "10",
        "vatli": "50",
        "mp": "5",
        "thoigian": "2000",
        "rong": "512",
        "cao": "64",
        "x": "-20",
        "sohinh": "8",
        "mota": "Tạo ra một con mặt nuốt chửng đối phương,gây stvl + 50*lv kĩ năng."
    },
    {
        "id": "5",
        "ten": "Poisonous thunder",
        "img": "bug",
        "level": "15",
        "phep": "70",
        "hp": "0",
        "vatli": "0",
        "mp": "10",
        "thoigian": "3000",
        "rong": "720",
        "cao": "80",
        "x": "-20",
        "sohinh": "9",
        "mota": "Gọi một cơn mưa độc , dội thẳng vào đầu đối phương , gây stp + 70*lv kĩ năng."
    },
    {
        "id": "6",
        "ten": "Toxic light",
        "img": "dragon",
        "phep": "0",
        "hp": "0",
        "vatli": "70",
        "mp": "9",
        "thoigian": "2200",
        "rong": "760",
        "cao": "64",
        "level": "15",

        "x": "-30",
        "sohinh": "7",
        "mota": "Tạo ra một nguồn ánh sáng cực mạnh lao thẳng vào đối phương, gây stvl + 70*lv"
    },
    {
        "id": "7",
        "ten": "Electrical storm",
        "img": "electric",
        "phep": "0",
        "hp": "0",
        "vatli": "80",
        "y": "-50",
        "level": "25",
        "mp": "12",
        "thoigian": "2500",
        "rong": "560",
        "cao": "80",
        "pk": "ok",
        "sohinh": "7",
        "mota": "Tạo ra những luồng sét có sức mạnh đặc biệt đánh thẳng vào đối phương gây stvl + 80*lv"
    },
    {
        "id": "8",
        "buff": "hoihp",
        "tile": "100",
        "time": "10000",
        "pk": "ok",
        "tacdung": "1",
        "ten": "Tái tạo",
        "img": "fairy",
        "phep": "0",
        "hp": "3",
        "level": "20",

        "vatli": "0",
        "mp": "30",
        "thoigian": "30000",
        "rong": "800",
        "cao": "80",
        "sohinh": "10",
        "mota": "Hồi phục 1*lv% hp mỗi giây."
    },
    {
        "id": "9",
        "ten": "Sandstorms",
        "img": "fighting",
        "phep": "95",
        "hp": "0",
        "vatli": "0",
        "level": "25",
        "mp": "20",
        "thoigian": "3000",
        "rong": "1360",
        "w": 50,
        "h": 50,
        "x": "-20",
        "y": "-10",
        "cao": "80",
        "sohinh": "17",
        "mota": "Tạo một làn sóng cát làm đối phương choáng váng gây stp + 95*lv"
    },
    {
        "id": "10",
        "ten": "Burning",
        "img": "fire",
        "phep": "0",
        "hp": "0",
        "vatli": "90",
        "mp": "11",
        "level": "30",
        "buff": "bong",
        "tile": "10",
        "time": "3000",
        "x": "-20",
        "y": "-20",
        "w": 50,
        "h": 50,
        "thoigian": "3000",
        "rong": "640",
        "cao": "80",
        "sohinh": "8",
        "mota": "Biến ra một ngọn lửa gây stvl + 90*lv"
    },
    {
        "id": "11",
        "ten": "whirlwind of wind",
        "img": "flying",
        "phep": "90",
        "hp": "0",
        "w": 50,
        "level": "30",
        "h": 50,
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "vatli": "0",
        "mp": "15",
        "pk": "ok",
        "thoigian": "2500",
        "rong": "800",
        "cao": "80",
        "sohinh": "10",
        "mota": "Cơn lóc xoáy mạnh gây cho kẻ địch trúng stp + 90*lv kĩ năng."
    },

    {
        "id": "13",
        "ten": "Leaf darts",
        "img": "grass",
        "phep": "0",
        "hp": "0",
        "vatli": "100",
        "mp": "20",
        "level": "30",
        "pk": "ok",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "thoigian": "2000",
        "rong": "1090",
        "cao": "81",
        "w": "50",
        "h": "40",
        "sohinh": "10",
        "mota": "Tri triển một phi tiêu thẳng vào đối phương gây stvl + 100*lv"
    },
    {
        "id": "14",
        "ten": "Thunder groaned",
        "img": "ground",
        "phep": "0",
        "hp": "0",
        "vatli": "1024",
        "mp": "100",
        "level": "40",
        "w": "50",
        "x": -20,
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "h": "50",
        "thoigian": "70000",
        "rong": "320",
        "cao": "80",
        "sohinh": "4",
        "mota": "Gọi một cơn mưa điện , gây sốc cho đối thủ stvl + 1024*lv"
    },
    {
        "id": "15",
        "ten": "Ice sword",
        "img": "ice",
        "phep": "85",
        "hp": "0",
        "pk": "ok",
        "buff": "dongbang",
        "tacdung": "3",
        "level": "25",
        "tile": "10",
        "time": "3000",
        "vatli": "0",
        "mp": "5",
        "thoigian": "1000",
        "rong": "650",
        "cao": "74",
        "sohinh": "6",
        "mota": "Phi thằng những cung tên băng vào đối thủ, gây stp + 85*lv"
    },
    {
        "id": "16",
        "ten": "Cột sáng",
        "img": "normal",
        "phep": "75",
        "hp": "0",
        "vatli": "0",
        "mp": "5",
        "level": "25",
        "thoigian": "3000",
        "rong": "1760",
        "cao": "80",
        "x": -30,
        "sohinh": "22",
        "mota": "Tạo một nguồn ánh sáng rồi làm nổ tung mục tiêu,gây stp + 75*lv "
    },

    {
        "id": "18",
        "ten": "Cào",
        "img": "rock",
        "phep": "0",
        "hp": "0",
        "goto": "1",
        "level": "25",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "vatli": "65",
        "mp": "3",
        "thoigian": "3000",
        "rong": "640",
        "cao": "80",
        "w": 50,
        h: 50,
        "x": "-20",
        "sohinh": "8",
        "mota": "Tạo vết sước , gây stvl + 65*lv"
    },
    {
        "id": "19",
        "ten": "Brick rain",
        "img": "steel",
        "phep": "0",
        "hp": "0",
        "level": "40",
        "x": "-20",
        "y": "-20",
        "vatli": "700",
        "mp": "90",
        "buff": "choang",
        "tile": "55",
        "time": "3000",
        "thoigian": "90000",
        "rong": "640",
        "cao": "80",
        "w": 50,
        h: 50,
        "sohinh": "8",
        "mota": "Gây cho đối thủ stvl + 700*lv"
    },
    {
        "id": "20",
        "ten": "Dare to water",
        "img": "water",
        "phep": "0",
        "hp": "0",
        "level": "25",
        "vatli": "80",
        "x": "-20",
        "w": 50,
        h: 50,
        "mp": "10",
        "thoigian": "4000",
        "rong": "1120",
        "cao": "80",
        "sohinh": "14",
        "mota": "Tạo một dòng nước siết gây cho đối thủ 80*%+stvl"
    },
    {
        "id": "29",
        "ten": "Hurricane",
        "img": "kkk456k",
        "phep": "0",
        "hp": "0",
        "vatli": "90",
        "mp": "10",
        "w": 50,
        h: 50,
         "level": "30",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "thoigian": "1000",
        "rong": "186",
        "cao": "64",
        "pk": "ok",
        "sohinh": "3",
        "mota": "Ném một cơn cuồng phong với sức mạnh uy ngang của trời đất cuấn mọi kẻ địch khi trúng đòn ! gây  90*%+stvl"
    },
    {
        "id": "32",
        "ten": "Dịch chuyển",
        "img": "kkk456r",
        "phep": "0",
        "hp": "0",
        "vatli": "0",
        "mp": "2",
        "thoigian": "200",
        "rong": "240",
        "cao": "48",
        "x": "-10",
        "y": "-20",
        "sohinh": "5",
        "mota": "Đóng băng đối thủ trong 1s,gây 50*lv+st vật lí."
    },
    {
        "id": "33",
        "ten": "Đánh thường",
        "img": "n6",
        "phep": "0",
        "hp": "0",
        "vatli": "20",
        "mp": "2",
        "thoigian": "1000",
        "rong": "192",
        "cao": "30",
        "sohinh": "6",
        "mota": "Gây 20*lv+st vật lí."
    },
    {
        "id": "34",
        "ten": "Cường hóa",
        "img": "n0",
        "phep": "0",
        "hp": "0",
        "vatli": "0",
        "mp": "2",
        "thoigian": "200",
        "rong": "174",
        "cao": "50",
        "sohinh": "3",
        "mota": "Gây 40*lv+st vật lí."
    },
    {
        "id": "35",
        "ten": "DCTT",
        "img": "dctt",
        "phep": "0",
        "hp": "0",
        "vatli": "0",
        "mp": "2",
        "thoigian": "200",
        "rong": "72",
        "cao": "30",
        "sohinh": "3",
        "mota": "Gây 40*lv+st vật lí."
    },

    {
        "id": "36",
        "ten": "Darts",
        "img": "k5kfg",
        "phep": "0",
        "hp": "0",
        "level": "30",
        "pk": "ok",
        "vatli": "40",
        "mp": "2",
        "thoigian": "1000",
        "rong": "44",
        "cao": "19",
        "sohinh": "2",
        "mota": "ném một phi tiêu Gây 40*lv+st vật lí."
    },

    {
        "id": "37",
        "ten": "Hand of fire",
        "img": "dkfldlkdg",
        "phep": "450",
        "hp": "0",
        "vatli": "0",
        "mp": "65",
        "level": "35",
        "thoigian": "30000",
        "rong": "258",
        "cao": "94",
        "w": 60,
        h: 60,
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "sohinh": "3",
        "x": "-30",
        "mota": "Một bàn tay dung nham hất tung đối phương gây 450*level + stp"
    },



    {
        "id": "38",
        "ten": "Ice storm",
        "img": "gkk46",
        "phep": "0",
        "hp": "0",
        "pk": "ok",
        "vatli": "70",
        "mp": "11",
        "buff": "dongbang",
        "tacdung": "3",
        "level": "30",
        "tile": "10",
        "time": "3000",
        "thoigian": "1500",
        "rong": "416",
        "cao": "110",
        "w": "52",
        "h": "54",
        "sohinh": "4",
        "mota": "Một cơn giông mạnh ! Lao vào kẻ thù ! Gây 85*level + stvl."
    },

    {
        "id": "39",
        "ten": "Fire unicorn",
        "img": "kfghkrkyk4o56klgrfkhg",
        "img1": "rkdglkdflgk5",
        "img0": "kfghkrkyk4o56klgrfkhg",
        "pk": "ok",
        "phep": "0",
        "hp": "0",
       "level": "35",
        "buff": "bong",
        "tile": "10",
        "tacdung" : "3",
        "time": "3000",
        "vatli": "95",
        "mp": "15",
        "thoigian": "2500",
        "rong": "720",
        "cao": "116",
        "x": "-50",
        "sohinh": "4",
        "w": "85",
        "h": "57",
        "mota": "Gọi hỏa kì lân ! Lao vào kẻ thù ! Gây 95*level + stvl."
    },

    {
        "id": "40",
        "buff": "dongbang",
        "tile": "13",
        "time": "5000",
        "tacdung": "3",
        "ten": "Ice showers",
        "img": "kfmhmfgh4",
        "phep": "115",
        "level": "35",
        "hp": "0",
        "vatli": "0",
        "mp": "25",
        "thoigian": "2500",
        "rong": "1430",
        "cao": "120",
        "x": "-10",
        "sohinh": "11",
        "w": "65",
        "h": "64",
        "mota": "Một cơn mưa băng ! Lao vào kẻ thù ! Gây 115*level + stp."
    },

    {
        "id": "41",
        "ten": "Wind blades",
        "img": "dkgkdfgdfg_1",
        "img1": "dfgldgdf_2",
        "img0": "dkgkdfgdfg_1",
        "pk": "1",
        "phep": "0",
        "level": "40",
        "hp": "0",
        "vatli": "99",
        "mp": "10",
        "thoigian": "2000",
        "rong": "600",
        "cao": "76",
        "buff": "choang",
        "tile": "15",
        "time": "3000",
        "x": "-50",
        "sohinh": "5",
        "w": "85",
        "h": "57",
        "mota": "Một lưỡi hái bằng gió , tỉ lệ 15% gây choáng cho đối phương trong 3s ! Lao nhanh tới kẻ thù gây 99*level + stvl"
    },


    {
        "id": "42",
        "ten": "Bow arrow",
        "img": "Small444",
        "img1": "coddgd",
        "img0": "Small444",
        "pk": "ok",
        "level": "20",
        "phep": "0",
        "hp": "0",
        "vatli": "30",
        "mp": "5",
        "thoigian": "1500",
        "rong": "36",
        "cao": "32",
        "x": "-50",
        "sohinh": "1",
        "w": "36",
        "h": "32",
        "buff": "dongbang",
        "tacdung": "3",

        "tile": "10",
        "time": "3000",
        "mota": "Một cung tên băng bắn vào đối phương. 30*level + stvl."
    },

    {
        "id": "43",
        "ten": "Two Bow arrows",
        "img": "Small447",
        "img1": "smal4645",
        "img0": "Small447",
        "pk": "ok",
        "level": "25",
        "phep": "0",
        "hp": "0",
        "vatli": "50",
        "mp": "7",
        "thoigian": "1700",
        "rong": "46",
        "cao": "20",
        "x": "-50",
        "sohinh": "1",
        "w": "46",
        "h": "20",
        "buff": "dongbang",
        "tacdung": "3",
        "tile": "15",
        "time": "3000",
        "mota": "Hai cung tên băng bắn vào đối phương. 50*level + stvl."
    },

    {
        "id": "44",
        "ten": "Three Arrow bows",
        "img": "Small453",
        "img1": "hdfgdfghdfgh",
        "img0": "Small453",
        "pk": "ok",
        "phep": "0",
        "hp": "0",
        "level": "30",
        "vatli": "70",
        "mp": "9",
        "thoigian": "1800",
        "rong": "54",
        "cao": "38",
        "x": "-50",
        "sohinh": "1",
        "w": "54",
        "h": "38",
        "buff": "dongbang",
        "tacdung": "3",
        "tile": "20",
        "time": "3000",
        "mota": "Ba cung tên băng bắn vào đối phương. 70*level + stvl."
    },


    {
        "id": "45",
        "ten": "Fire heaven sword",
        "img": "gkdsgdfg",
        "img1": "sdfgf_2",
        "img0": "gkdsgdfg",
        "level": "30",
        "pk": "1",
        "phep": "0",
        "hp": "0",
        "vatli": "110",
        "mp": "22",
        "thoigian": "1500",
        "rong": "180",
        "cao": "14",
        "x": "-50",
        "y": "20",
        "sohinh": "2",
        "w": "85",
        "h": "12",
        "buff": "bong",
        "tile": "10",
        "time": "3000",
        "mota": "Thanh kiếm toàn lửa ! Lao nhanh tới kẻ thù gây 110*level + stvl"
    },

    {
        "id": "46",
        "ten": "Judgment of the gods",
        "img": "ghfghdf",
        "pk": "1",
        "level": "40",
        "phep": "450",
        "hp": "0",
        "vatli": "0",
        "mp": "33",
        "thoigian": "14500",
        "rong": "660",
        "cao": "124",
        "x": "-25",
        "y": "0",
        "sohinh": "6",
        "w": "85",
        "h": "65",
        "buff": "choang",
        "tile": "25",
        "time": "3000",
        "mota": "Giáng xuống một tia xét chuyển hóa thành vụ nổ nghìn vôn ! Lao nhanh tới kẻ thù gây 450*level + STP"
    },

    {
        "id": "47",
        "ten": "Blow away",
        "img": "dsfgsdfgsd",
        "img1": "dgsdfgsd_a",
        "img0": "dsfgsdfgsd",
        "pk": "1",
        "level": "40",
        "phep": "0",
        "hp": "0",
        "vatli": "77",
        "mp": "19",
        "thoigian": "1500",
        "rong": "240",
        "cao": "88",
        "x": "-50",
        "y": "0",
        "sohinh": "2",
        "w": "85",
        "h": "65",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "mota": "Bàn tay tu đùng ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 77*level + stvl"
    },

    {
        "id": "48",
        "ten": "Fire Phoenix",
        "img": "etyreyret",
        "img1": "dgsdfg4",
        "img0": "etyreyret",
        "pk": "ok",
        "level": "50",

        "phep": "0",
        "hp": "0",
        "vatli": "150",
        "mp": "33",
        "thoigian": "2500",
        "rong": "1640",
        "cao": "124",
        "x": "-50",
        "y": "0",
        "sohinh": "10",
        "w": "85",
        "h": "65",
        "buff": "bong",
        "tile": "10",
        "time": "3000",
        "mota": "Triệu tập phượng hoàng lửa lao vào đối thủ ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "49",
        "ten": "Missile target",
        "img": "hgfghdfg",
        "pk": "ok",
        "level": "50",
        "phep": "0",
        "hp": "0",
        "vatli": "150",
        "mp": "35",
        "thoigian": "2500",
        "rong": "376",
        "cao": "98",
        "x": "-50",
        "y": "0",
        "sohinh": "4",
        "w": "44",
        "h": "50",
        "buff": "bong",
        "tile": "10",
        "time": "3000",
        "mota": "Một phi tiêu lao vào đối thủ với sát thương cực đại ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "50",
        "buff": "bong",
        "tile": "15",
        "time": "5000",
        "tacdung": "1",
        "ten": "Dragon legendary",
        "level": "55",
        "img": "a43532453245",
        "img1": "b34345345",
        "img0": "a43532453245",
        "pk": "ok",
        "phep": "150",
        "hp": "0",
        "vatli": "0",
        "mp": "40",
        "thoigian": "1500",
        "rong": "1000",
        "cao": "116",
        "x": "-50",
        "y": "0",
        "sohinh": "5",
        "w": "85",
        "h": "65",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stphep"
    },

    {
        "id": "51",
        "ten": "Ice Dragon",
        "img": "tyutyu5",
        "level": "55",
        "img1": "b4543646",
        "img0": "tyutyu5",
        "pk": "ok",
        "phep": "0",
        "hp": "0",
        "vatli": "150",
        "mp": "33",
        "thoigian": "4500",
        "rong": "808",
        "cao": "124",
        "x": "-50",
        "y": "0",
        "sohinh": "4",
        "w": "85",
        "h": "65",
        "buff": "dongbang",
        "tacdung": "3",

        "tile": "15",
        "time": "3000",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },
    {
        "id": "52",
        "level": "55",
        "ten": "Ribbon bows",
        "img": "gfhdfh_a",
        "img1": "dfgf_b",
        "img0": "gfhdfh_a",
        "pk": "1",
        "phep": "0",
        "hp": "0",
        "vatli": "150",
        "mp": "25",
        "thoigian": "1500",
        "rong": "272",
        "cao": "114",
        "x": "-50",
        "y": "0",
        "sohinh": "4",
        "w": "68",
        "h": "65",
        "buff": "dongbang",
        "tacdung": "3",
        "tile": "30",
        "time": "4000",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "53",
        "ten": "Đoạt mệnh",
        "img": "2345345w",
        "pk": "ok",
        "level": "45",

        "phep": "0",
        "hp": "0",
        "vatli": "70",
        "mp": "15",
        "thoigian": "1500",
        "rong": "480",
        "cao": "120",
        "x": "-50",
        "y": "0",
        "sohinh": "4",
        "w": "68",
        "h": "65",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "mota": "Lao nhanh tới kẻ thù gây 70*level + stvl"
    },


    {
        "id": "54",
        "buff": "troi",
        "tile": "15",
        "level": "55",
        "time": "15000",
        "ten": "Dragon horse",
        "img": "sdfggdgf",
        "img1": "dfgdgd_",
        "img0": "sdfggdgf",
        "pk": "1",
        "phep": "0",
        "hp": "0",
        "vatli": "150",
        "mp": "25",
        "thoigian": "3500",
        "rong": "792",
        "cao": "132",
        "x": "-50",
        "y": "0",
        "sohinh": "4",
        "w": "85",
        "h": "65",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "55",
        "ten": "Devils scythe",
        "img": "fghdfgh",
        "img1": "tytytuut_a",
        "img0": "fghdfgh",
        "pk": "1",
        "level": "40",
        "phep": "0",
        "hp": "0",
        "vatli": "100",
        "mp": "25",
        "thoigian": "1500",
        "rong": "1536",
        "cao": "150",
        "x": "-50",
        "y": "-20",
        "sohinh": "8",
        "w": "85",
        "h": "65",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 100*level + stvl"
    },

    {
        "id": "56",
        "ten": "Quái đánh",
        "img": "345343245",
        "pk": "ok",
        "buff": "choang",
        "tile": "10",
        "time": "3000",
        "phep": "0",
        "hp": "0",
        "vatli": "0",
        "mp": "10",
        "thoigian": "1500",
        "rong": "56",
        "cao": "28",
        "x": "0",
        "y": "0",
        "sohinh": "2",
        "w": "28",
        "h": "28",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "57",
        "ten": "Văng máu",
        "img": "qqqqq_",
        "img1": "srq_b",
        "img0": "qqqqq_",
        "pk": "1",
        "phep": "0",
        "hp": "0",
        "vatli": "0",
        "mp": "10",
        "thoigian": "1500",
        "rong": "87",
        "cao": "23",
        "x": "25",
        "y": "20",
        "sohinh": "3",
        "w": "29",
        "h": "23",
        "mota": "Truyền thuyết của rồng ! ! Sẵn sàng đẩy văng đối thủ. ! Lao nhanh tới kẻ thù gây 150*level + stvl"
    },

    {
        "id": "58",
        "buff": "hs",
        "tile": "100",
        "time": "4000",
        "pk": "ok",
        "tacdung": "10",
        "ten": "Hồi Phục",
        "img": "fairy",
        "phep": "0",
        "hp": "3",
                "level": "20",

        "vatli": "0",
        "mp": "30",
        "thoigian": "20000",
        "rong": "800",
        "cao": "80",
        "sohinh": "10",
        "mota": "Hồi sinh đồng đội."
    },
];