var kinang = [
    
        {
        "id": 30701808,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_0",
        "level": 5,
        "phep": 0,
        "vatli": 15,
        "hp": 0,
        "type": "Normal",
        "mp": 5.5,
        "thoigian": 2750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 15 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 57866617,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_1",
        "level": 5,
        "phep": 0,
        "vatli": 30,
        "hp": 0,
        "type": "Fire",
        "mp": 6,
        "thoigian": 3000,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 30 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 81201275,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_2",
        "level": 5,
        "phep": 20,
        "vatli": 0,
        "hp": 0,
        "type": "Water",
        "mp": 6.75,
        "thoigian": 3375,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 20 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 71120386,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_3",
        "level": 5,
        "phep": 25,
        "vatli": 0,
        "hp": 0,
        "type": "Electric",
        "mp": 6.25,
        "thoigian": 3125,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 25 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 96856881,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_4",
        "level": 5,
        "phep": 0,
        "vatli": 10,
        "hp": 0,
        "type": "Grass",
        "mp": 5.5,
        "thoigian": 2750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 10 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 56251366,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_5",
        "level": 5,
        "phep": 30,
        "vatli": 0,
        "hp": 0,
        "type": "Ice",
        "mp": 7.5,
        "thoigian": 3750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 30 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 6721387,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_6",
        "level": 5,
        "phep": 0,
        "vatli": 35,
        "hp": 0,
        "type": "Fighting",
        "mp": 7.5,
        "thoigian": 2750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 35 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 68469681,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_7",
        "level": 5,
        "phep": 30,
        "vatli": 0,
        "hp": 0,
        "type": "Poison",
        "mp": 8,
        "thoigian": 4000,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 30 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 62952708,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_8",
        "level": 5,
        "phep": 0,
        "vatli": 35,
        "hp": 0,
        "type": "Ground",
        "mp": 7.5,
        "thoigian": 3750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 35 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 86507481,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_9",
        "level": 5,
        "phep": 0,
        "vatli": 19,
        "hp": 0,
        "type": "Flying",
        "mp": 5.75,
        "thoigian": 2875,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 19 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 66425442,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_10",
        "level": 5,
        "phep": 23,
        "vatli": 0,
        "hp": 0,
        "type": "Psychic",
        "mp": 8,
        "thoigian": 4000,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 23 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 6897708,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_11",
        "level": 5,
        "phep": 0,
        "vatli": 15,
        "hp": 0,
        "type": "Bug",
        "mp": 5.25,
        "thoigian": 3750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 15 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 35325631,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_12",
        "level": 5,
        "phep": 0,
        "vatli": 19,
        "hp": 0,
        "type": "Rock",
        "mp": 7.5,
        "thoigian": 3750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 19 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 77038683,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_13",
        "level": 5,
        "phep": 29,
        "vatli": 0,
        "hp": 0,
        "type": "Ghost",
        "mp": 12.5,
        "thoigian": 3750,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 29 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 18488031,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_14",
        "level": 5,
        "phep": 30,
        "vatli": 0,
        "hp": 0,
        "type": "Dragon",
        "mp": 12.5,
        "thoigian": 3250,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 30 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 5288802,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_15",
        "level": 5,
        "phep": 30,
        "vatli": 0,
        "hp": 0,
        "type": "Dark",
        "mp": 12.5,
        "thoigian": 4700,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 30 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 66212206,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_16",
        "level": 5,
        "phep": 15,
        "vatli": 0,
        "hp": 0,
        "type": "Steel",
        "mp": 12.5,
        "thoigian": 5000,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 15 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 90963142,
        "id2": 1,
        "ten": "Gnawing",
        "img": "n_17",
        "level": 5,
        "phep": 10,
        "vatli": 0,
        "hp": 0,
        "type": "Fairy",
        "mp": 12.5,
        "thoigian": 5000,
        "rong": 320,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 5,
        "mota": "tạo ra một hàm răng nhọn nuốt chửng đối thủ. Gây Sát 10 thương phép* cấp độ kĩ năng. "
    }
,


    {
        "id": 95332040,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_0",
        "level": 10,
        "phep": 0,
        "vatli": 25,
        "hp": 0,
        "type": "Normal",
        "mp": 11,
        "thoigian": 3850,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 25 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 78397018,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_1",
        "level": 10,
        "phep": 0,
        "vatli": 40,
        "hp": 0,
        "type": "Fire",
        "mp": 12,
        "thoigian": 4200,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 40 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 86095013,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_2",
        "level": 10,
        "phep": 35,
        "vatli": 0,
        "hp": 0,
        "type": "Water",
        "mp": 13.5,
        "thoigian": 4725,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 35 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 3261314,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_3",
        "level": 10,
        "phep": 35,
        "vatli": 0,
        "hp": 0,
        "type": "Electric",
        "mp": 12.5,
        "thoigian": 4375,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 35 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 6567440,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_4",
        "level": 10,
        "phep": 0,
        "vatli": 25,
        "hp": 0,
        "type": "Grass",
        "mp": 11,
        "thoigian": 3850,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 25 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 89186804,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_5",
        "level": 10,
        "phep": 36,
        "vatli": 0,
        "hp": 0,
        "type": "Ice",
        "mp": 15,
        "thoigian": 5250,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 36 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 50248366,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_6",
        "level": 10,
        "phep": 0,
        "vatli": 42,
        "hp": 0,
        "type": "Fighting",
        "mp": 15,
        "thoigian": 3850,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 42 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 7277201,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_7",
        "level": 10,
        "phep": 52,
        "vatli": 0,
        "hp": 0,
        "type": "Poison",
        "mp": 16,
        "thoigian": 5600,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 52 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 73138048,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_8",
        "level": 10,
        "phep": 0,
        "vatli": 48,
        "hp": 0,
        "type": "Ground",
        "mp": 15,
        "thoigian": 5250,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 48 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 93964653,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_9",
        "level": 10,
        "phep": 0,
        "vatli": 30,
        "hp": 0,
        "type": "Flying",
        "mp": 11.5,
        "thoigian": 4025,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 30 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 98943467,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_10",
        "level": 10,
        "phep": 40,
        "vatli": 0,
        "hp": 0,
        "type": "Psychic",
        "mp": 16,
        "thoigian": 5600,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 40 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 60701472,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_11",
        "level": 10,
        "phep": 0,
        "vatli": 45,
        "hp": 0,
        "type": "Bug",
        "mp": 10.5,
        "thoigian": 5250,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 45 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 91733388,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_12",
        "level": 10,
        "phep": 0,
        "vatli": 29,
        "hp": 0,
        "type": "Rock",
        "mp": 15,
        "thoigian": 5250,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 29 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 80223535,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_13",
        "level": 10,
        "phep": 50,
        "vatli": 0,
        "hp": 0,
        "type": "Ghost",
        "mp": 25,
        "thoigian": 5250,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 50 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 25775637,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_14",
        "level": 10,
        "phep": 50,
        "vatli": 0,
        "hp": 0,
        "type": "Dragon",
        "mp": 25,
        "thoigian": 4550,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 50 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 72830854,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_15",
        "level": 10,
        "phep": 35,
        "vatli": 0,
        "hp": 0,
        "type": "Dark",
        "mp": 25,
        "thoigian": 6580,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 35 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 81286431,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_16",
        "level": 10,
        "phep": 25,
        "vatli": 0,
        "hp": 0,
        "type": "Steel",
        "mp": 25,
        "thoigian": 7000,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 25 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 25951025,
        "id2": 2,
        "ten": "Poison fire",
        "img": "r_17",
        "level": 10,
        "phep": 20,
        "vatli": 0,
        "hp": 0,
        "type": "Fairy",
        "mp": 25,
        "thoigian": 7000,
        "rong": 384,
        "cao": 64,
        "w": 50,
        "h": 50,
        "sohinh": 6,
        "mota": "tạo ra ngọn lửa tìm độc làm đối phương tê liệt. Gây Sát 20 thương phép* cấp độ kĩ năng. "
    }
    
    ,
    
    {
        "id": 8525312,
        "id2": 3,
        "ten": "Funger red",
        "img": "b0",
        "img0": "b0",
        "img1": "b0",
        "level": 15,
        "phep": 0,
        "vatli": 40,
        "hp": 0,
        "type": "Normal",
        "mp": 16.5,
        "buff": "bong",
        "tile": 4,
        "time": 3300,
        "tacdung": 1,
        "thoigian": 3850,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 40 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 23876251,
        "id2": 3,
        "ten": "Funger red",
        "img": "b1",
        "img0": "b1",
        "img1": "b1",
        "level": 15,
        "phep": 0,
        "vatli": 55,
        "hp": 0,
        "type": "Fire",
        "mp": 18,
        "buff": "bong",
        "tile": 6,
        "time": 3600,
        "tacdung": 1,
        "thoigian": 4200,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 55 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 97329475,
        "id2": 3,
        "ten": "Funger red",
        "img": "b2",
        "img0": "b2",
        "img1": "b2",
        "level": 15,
        "phep": 50,
        "vatli": 0,
        "hp": 0,
        "type": "Water",
        "mp": 20.25,
        "buff": "bong",
        "tile": 6,
        "time": 4050,
        "tacdung": 1,
        "thoigian": 4725,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 50 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 32822457,
        "id2": 3,
        "ten": "Funger red",
        "img": "b3",
        "img0": "b3",
        "img1": "b3",
        "level": 15,
        "phep": 50,
        "vatli": 0,
        "hp": 0,
        "type": "Electric",
        "mp": 18.75,
        "buff": "bong",
        "tile": 6,
        "time": 3750,
        "tacdung": 1,
        "thoigian": 4375,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 50 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 51577556,
        "id2": 3,
        "ten": "Funger red",
        "img": "b4",
        "img0": "b4",
        "img1": "b4",
        "level": 15,
        "phep": 0,
        "vatli": 45,
        "hp": 0,
        "type": "Grass",
        "mp": 16.5,
        "buff": "bong",
        "tile": 4,
        "time": 3300,
        "tacdung": 1,
        "thoigian": 3850,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 45 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 63702766,
        "id2": 3,
        "ten": "Funger red",
        "img": "b5",
        "img0": "b5",
        "img1": "b5",
        "level": 15,
        "phep": 60,
        "vatli": 0,
        "hp": 0,
        "type": "Ice",
        "mp": 22.5,
        "buff": "bong",
        "tile": 16,
        "time": 4500,
        "tacdung": 1,
        "thoigian": 5250,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 60 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 31609551,
        "id2": 3,
        "ten": "Funger red",
        "img": "b6",
        "img0": "b6",
        "img1": "b6",
        "level": 15,
        "phep": 0,
        "vatli": 50,
        "hp": 0,
        "type": "Fighting",
        "mp": 22.5,
        "buff": "bong",
        "tile": 6,
        "time": 3300,
        "tacdung": 1,
        "thoigian": 3850,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 50 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 37849810,
        "id2": 3,
        "ten": "Funger red",
        "img": "b7",
        "img0": "b7",
        "img1": "b7",
        "level": 15,
        "phep": 59,
        "vatli": 0,
        "hp": 0,
        "type": "Poison",
        "mp": 24,
        "buff": "bong",
        "tile": 16,
        "time": 4800,
        "tacdung": 1,
        "thoigian": 5600,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 59 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 55505684,
        "id2": 3,
        "ten": "Funger red",
        "img": "b8",
        "img0": "b8",
        "img1": "b8",
        "level": 15,
        "phep": 0,
        "vatli": 55,
        "hp": 0,
        "type": "Ground",
        "mp": 22.5,
        "buff": "bong",
        "tile": 4,
        "time": 4500,
        "tacdung": 1,
        "thoigian": 5250,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 55 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 23928741,
        "id2": 3,
        "ten": "Funger red",
        "img": "b9",
        "img0": "b9",
        "img1": "b9",
        "level": 15,
        "phep": 0,
        "vatli": 45,
        "hp": 0,
        "type": "Flying",
        "mp": 17.25,
        "buff": "bong",
        "tile": 4,
        "time": 3450,
        "tacdung": 1,
        "thoigian": 4025,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 45 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 10104268,
        "id2": 3,
        "ten": "Funger red",
        "img": "b10",
        "img0": "b10",
        "img1": "b10",
        "level": 15,
        "phep": 60,
        "vatli": 0,
        "hp": 0,
        "type": "Psychic",
        "mp": 24,
        "buff": "bong",
        "tile": 4,
        "time": 4800,
        "tacdung": 1,
        "thoigian": 5600,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 60 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 38093647,
        "id2": 3,
        "ten": "Funger red",
        "img": "b11",
        "img0": "b11",
        "img1": "b11",
        "level": 15,
        "phep": 0,
        "vatli": 55,
        "hp": 0,
        "type": "Bug",
        "mp": 15.75,
        "buff": "bong",
        "tile": 4,
        "time": 4500,
        "tacdung": 1,
        "thoigian": 5250,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 55 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 27126174,
        "id2": 3,
        "ten": "Funger red",
        "img": "b12",
        "img0": "b12",
        "img1": "b12",
        "level": 15,
        "phep": 0,
        "vatli": 46,
        "hp": 0,
        "type": "Rock",
        "mp": 22.5,
        "buff": "bong",
        "tile": 4,
        "time": 4500,
        "tacdung": 1,
        "thoigian": 5250,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 46 thương vật lí* cấp độ kĩ năng. "
    },
    {
        "id": 41179289,
        "id2": 3,
        "ten": "Funger red",
        "img": "b13",
        "img0": "b13",
        "img1": "b13",
        "level": 15,
        "phep": 65,
        "vatli": 0,
        "hp": 0,
        "type": "Ghost",
        "mp": 37.5,
        "buff": "bong",
        "tile": 16,
        "time": 4500,
        "tacdung": 1,
        "thoigian": 5250,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 65 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 22321429,
        "id2": 3,
        "ten": "Funger red",
        "img": "b14",
        "img0": "b14",
        "img1": "b14",
        "level": 15,
        "phep": 85,
        "vatli": 0,
        "hp": 0,
        "type": "Dragon",
        "mp": 37.5,
        "buff": "bong",
        "tile": 11,
        "time": 3900,
        "tacdung": 1,
        "thoigian": 4550,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 85 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 17390472,
        "id2": 3,
        "ten": "Funger red",
        "img": "b15",
        "img0": "b15",
        "img1": "b15",
        "level": 15,
        "phep": 75,
        "vatli": 0,
        "hp": 0,
        "type": "Dark",
        "mp": 37.5,
        "buff": "bong",
        "tile": 11,
        "time": 5640,
        "tacdung": 1,
        "thoigian": 6580,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 75 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 7635582,
        "id2": 3,
        "ten": "Funger red",
        "img": "b16",
        "img0": "b16",
        "img1": "b16",
        "level": 15,
        "phep": 85,
        "vatli": 0,
        "hp": 0,
        "type": "Steel",
        "mp": 37.5,
        "buff": "bong",
        "tile": 4,
        "time": 6000,
        "tacdung": 1,
        "thoigian": 7000,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 85 thương phép* cấp độ kĩ năng. "
    },
    {
        "id": 52217497,
        "id2": 3,
        "ten": "Funger red",
        "img": "b17",
        "img0": "b17",
        "img1": "b17",
        "level": 15,
        "phep": 60,
        "vatli": 0,
        "hp": 0,
        "type": "Fairy",
        "mp": 37.5,
        "buff": "bong",
        "tile": 21,
        "time": 6000,
        "tacdung": 1,
        "thoigian": 7000,
        "rong": 376,
        "cao": 98,
        "w": 50,
        "h": 50,
        "sohinh": 4,
        "mota": "Ném một phi tiêu thẳng vào người đối thủ. Gây Sát 60 thương phép* cấp độ kĩ năng. "
    }
    
    
    
    
    
    
    ];